### ISSUE TITLE
Editor gets real slow and crashes on comments 

### ISSUE THREAD

**Issue by nmccready** [markwainwright/atom-linter-coffee-variables#6]
Not sure if this is entirely this libs fault or maybe normal coffee lint. While every thing seems to be fine ; I constantly have been seeing comments make atom come to a crawl. Not sure why this is so hard on the system. Again not really sure how to help you except maybe output the stack of packages I have installed.

**Comment by markwainwright** [comment]
@nmccready 
Large comments shouldn't put too much load on this package because the package only re-runs ESLint if the compiled CoffeeScript has changed. This means changes to comments, or adding comments, won't trigger a full re-check on every keystroke.

Large files in general may cause slowdowns, because the package needs to compile the file to CoffeeScript every time. How many lines are in your file?

You could also enable Debug mode in the package config and open Atom's developer console. This will show you how long the package is taking to perform each step (compiling to CS and running through ESLint). If anything there seems excessive, let me know.

**Comment by Phydaux** [comment]
I get this issue too. On large files, say > 1000 LOC, simply writing comments can crash atom.

Here is a sample of the logs I get. Times vary from about 300ms to 900ms.

```
[linter-coffee-variables] Compiling to JS: 487.562ms
[linter-coffee-variables] Compiling to JS: 487.441ms
[linter-coffee-variables] Compiling to JS: 496.592ms
[linter-coffee-variables] Compiling to JS: 518.452ms
[linter-coffee-variables] Compiling to JS: 503.532ms
```

I think atom runs out of memory.

This doesn't happen when this package is disabled, or if I use version `0.2.0` of linter-coffee-variables.

**Comment by markwainwright** [comment]
Hi @Phydaux, thanks for the information. I'm not sure I ever tested it on files that large, and it taking that long to compile to JS could definitely cause slowdowns or crashes. I'll investigate to see what could be causing this since v0.2.0.

**Comment by nmccready** [comment]
This appears to be resolved in recent releases. I have not had problems in a while.

**Comment by nmccready** [comment]
Actually I take that back as today I got an error where the error reported invalid string length. Were atom got all slow again as well.

```
RangeError: Invalid string length
    at Object.stringify (native)
    at ~/.atom/packages/linter/lib/validate.coffee:53:25
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (~/.atom/packages/linter/lib/validate.coffee:27:14)
    at MessageRegistry.set (~/.atom/packages/linter/lib/message-registry.js:36:16)
    at ~/.atom/packages/linter/lib/linter.coffee:37:17
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at ~/.atom/packages/linter/lib/linter-registry.js:66:26
```

**Comment by markwainwright** [comment]
@nmccready:

I looked into that error a bit and it seems like it would happen when one of the error objects being passed to `linter` is a huge object that would take too much memory to serialize to JSON.

But looking at the objects that this package passes to `linter` (https://github.com/markwainwright/atom-linter-coffee-variables/blob/60a061171d14898c2d675c84a6612e524cc508a9/lib/linter-coffee-variables.coffee#L115-L121) it's hard to see how this could be the case.

Since all we know from the stack trace is that the error is coming from `linter` it's possible that it's being caused be a different `linter` plugin.

If you see this again please let me know what versions of both this package and `linter` you're using, and ideally give me the code that triggered it.

Thanks!

**Comment by nmccready** [comment]
Anyway the linter can utilize streaming? That way the memory footprint stays small and constant.

**Comment by nmccready** [comment]
Still having this issue daily on files < 200 lines.

**Comment by nmccready** [comment]
One thing I noticed in the code is the [cache](https://github.com/markwainwright/atom-linter-coffee-variables/blob/master/lib/linter-coffee-variables.coffee#L3) just grows with no limits. So the longer atom is open the more likely you will run into a problem. I would suggest a LRU cache here that is limited to  10 or so files. Also if you we could memozie the files being cached so they expire as well.

https://www.npmjs.com/package/lru
https://github.com/medikoo/memoizee

Lastly I looked at the code and things like [this](https://github.com/markwainwright/atom-linter-coffee-variables/blob/master/lib/linter-coffee-variables.coffee#L26-L30) and [this](https://github.com/markwainwright/atom-linter-coffee-variables/blob/master/lib/linter-coffee-variables.coffee#L153-L156) are syntactically beautiful. However anything using the array iterators is known to be **much much** slower than using `for in`(coffee -> regular for loop) or a `for loop`. I had examples of this on jspef.com, but sadly the site is down right now.

So in the end I think the above suggestions would help immensely. I will try to put a PR together.

@markwainwright

**Comment by nmccready** [comment]
It looks like memoizee has everything needed, it has expiration and an LRU. Ha, they both have it anyway I'll pick one.
