### ISSUE TITLE
(Question) How do I ignore global variables?

### ISSUE THREAD

**Issue by DavidLGoldberg** [markwainwright/atom-linter-coffee-variables#7]
I think some other es6 tools allow you do a comment /\* global <var> */

Awesome package btw!

**Comment by markwainwright** [comment]
@DavidLGoldberg 
Thanks! The best way, if your globals are standard for certain environments (`node`, `mocha`, `jquery` etc) is to set Environments in the package config. You can choose from anything supported by ESLint: http://eslint.org/docs/user-guide/configuring#specifying-environments

If you want specific per-file globals you can use a block comment (so that the comment is retained when compiled to JS) at the top of the file, e.g.

``` coffeescript
### globals foo ###
```

**Comment by DavidLGoldberg** [comment]
Ah, that's exactly what I wanted, I should have known how to do it :\ thanks!

**Comment by alinex** [comment]
Thanks, that helps me I added the following comment on top of my mocha test file:

```
### eslint-env node, mocha ###
```

**Comment by mjomble** [comment]
It might be a good idea to put this information in the README. I only found out about it by browsing the issues.
